### PR TITLE
Check And Mutate semantics should be the inverse of ValueFilter

### LINKED ISSUE #1348: Possible incorrect behavior in checkAndPut
From https://stackoverflow.com/questions/44174094/checkandput-always-succeeds

There are only tests for equality comparators in checkAnd*.
Add tests for "<" or ">" (non commutative comparators) and verify that their behavior is as defined in the documentation:
"GREATER operator means expected value > existing <=> add the put."

### PR DESCRIPTION
**Pull request by sduskis**
It's not clear why that is, but CheckAnd* CompareOps should be reversed in order for Bigtable to Comply with HBase.  This should fix #1348

### CODE REVIEW

**Comment by igorbernstein2** [comment]
LGTM

File: bigtable-hbase-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableTable.java [hunk 1]
```diff
@@ -701,6 +702,32 @@ protected boolean wasMutationApplied(
...
+   * For some reason, the ordering of CheckAndMutate operations is the inverse order of normal
+   * {@link ValueFilter} operations.
+   *
+   * @param compareOp
+   * @return the inverse of compareOp
+   */
+  private static CompareOp reverseCompareOp(CompareOp compareOp) {
+    switch (compareOp) {
+    case EQUAL:
+    case NOT_EQUAL:
```
Comment (rameshdharan) [inline bigtable-hbase-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableTable.java]: Shouldn't these be inverted also?

```
case EQUAL: 
   return CompareOp.NOT_EQUAL;
case NOT_EQUAL: 
   return CompareOp.EQUAL;
```

Doesn't look like this commit has tests for those cases but I believe the original poster encountered unexpected behavior even with strict equality?

File: bigtable-hbase-parent/bigtable-hbase-integration-tests/src/test/java/com/google/cloud/bigtable/hbase/TestCheckAndMutate.java [hunk 2]
```diff
@@ -285,4 +288,52 @@ public void testCheckAndMutate() throws IOException {
         row.containsColumn(SharedTestEnvRule.COLUMN_FAMILY, qualPut));
     table.close();
   }
+
+  @Test
+  public void testCompareOps() throws IOException {
```
Comment (rameshdharan) [inline bigtable-hbase-parent/bigtable-hbase-integration-tests/src/test/java/com/google/cloud/bigtable/hbase/TestCheckAndMutate.java]: I think we should add tests for CompareOp.EQUAL and CompareOp.NOT_EQUAL as well.
