### PR TITLE
Scans where start == end should be the same as a Get

### LINKED ISSUE #928: Scans where start == end should be the same as a Get
Externally-reported issue:

> When I submit a scan that has the same start and end row then i get this exception: 
> 
> ```
> INVALID_ARGUMENT: Error in field 'row_ranges' : Error in element #0 : start_key
> must be less than end_key 
> ```
>
> This will now require me to duplicate a bunch of code so that I can use a `Get` when there is only one row I am selecting.
>
> Can you treat those scans as gets the way that HBase does?

### PR DESCRIPTION
**Pull request by sduskis**
This should fix #928.

### CODE REVIEW

File: bigtable-hbase-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/read/ScanAdapter.java [hunk 1]
```diff
@@ -90,16 +90,17 @@ public RowFilter buildFilter(Scan scan, ReadHooks hooks) {
...
-              RowRange.newBuilder()
-                  .setStartKeyClosed(ByteString.copyFrom(scan.getStartRow()))
-                  .setEndKeyOpen(ByteString.copyFrom(scan.getStopRow()))));
+    RowSet.Builder rowSetBuilder = RowSet.newBuilder();
+    if (scan.isGetScan()) {
+      rowSetBuilder.addRowKeys(ByteString.copyFrom(scan.getStartRow()));
+    } else {
+      rowSetBuilder.addRowRanges(
+        RowRange.newBuilder().setStartKeyClosed(ByteString.copyFrom(scan.getStartRow()))
+            .setEndKeyOpen(ByteString.copyFrom(scan.getStopRow())));
```
Comment (rameshdharan) [inline bigtable-hbase-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/read/ScanAdapter.java]: Indentation here seems a bit inconsistent. Personally I'm fine with the style the way it was (with leading periods) but in both cases the indentation seems off (4 spaces instead of 2)?

**Comment by rameshdharan** [comment]
LGTM (except for the very minor indentation issue).
