### PR TITLE
Removing the buffered mutator "worker" behavior from dataflow.

### LINKED ISSUE #630: DataFlow CloudBigtableIO leaks threads
We have a DataFlow job that's structurally very similar to the [WordCount](https://cloud.google.com/dataflow/examples/wordcount-example#UnboundedData) example, reading from pubsub, producing per X minute windowed counts that are written to CBT.

We're using `0.2.3-SNAPSHOT` of `bigtable-hbase-dataflow` and `bigtable-hbase-1.1` in order to work around https://github.com/GoogleCloudPlatform/cloud-bigtable-client/issues/613.

When deploying our job late last week we discovered that it was failing with the DF workers unable to create more threads.

```
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1368)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.initializeAsyncMutators(BigtableBufferedMutator.java:206)
	at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.<init>(BigtableBufferedMutator.java:201)
	at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.<init>(BigtableBufferedMutator.java:174)
	at org.apache.hadoop.hbase.client.AbstractBigtableConnection$2.<init>(AbstractBigtableConnection.java:193)
	at org.apache.hadoop.hbase.client.AbstractBigtableConnection.getBufferedMutator(AbstractBigtableConnection.java:192)
	at com.google.cloud.bigtable.dataflow.CloudBigtableIO$CloudBigtableSingleTableWriteFn.getBufferedMutator(CloudBigtableIO.java:615)
	at com.google.cloud.bigtable.dataflow.CloudBigtableIO$CloudBigtableSingleTableWriteFn.processElement(CloudBigtableIO.java:640)
```

We SSH'd to one of the DF worker hosts and saw that the worker JVM process had some 32k+ threads. We attempted to redeploy our job a few times, each time hitting the same issue. 

The same job deployed the week before had functioned normally so we figured that maybe this issue was caused by some recent change to the CBT client and redeployed our job with an earlier CBT client commit (6cefa8195724eefc2a58428597e68ccdb9513482) instead, which works fine. 

Looking at the recent commit log I wonder if maybe 1433a527a192694b13862776500576e73126219b could be related to this.

We have not attempted to repro outside DataFlow.

### PR DESCRIPTION
**Pull request by sduskis**
This is the quickest way to fix #630.  It will have some potentially
negative performance impacts on dataflow writes compared to what
performance could be.  That said, there are other issues with
dataflow/bigtable that need solving in bigtable/dataflow that need
solving first.

### CODE REVIEW

File: bigtable-hbase-dataflow/src/main/java/com/google/cloud/bigtable/dataflow/CloudBigtableConfiguration.java [hunk 1]
```diff
@@ -178,6 +178,13 @@ public BigtableOptions toBigtableOptions() throws IOException {
    */
   public Configuration toHBaseConfig() {
     Configuration config = new Configuration();
+
```
Comment (kevinsi4508) [inline bigtable-hbase-dataflow/src/main/java/com/google/cloud/bigtable/dataflow/CloudBigtableConfiguration.java]: Instead of this, why don't we set BIGTABLE_ASYNC_MUTATOR_COUNT_DEFAULT to 0?

File: bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutator.java [hunk 2]
```diff
@@ -137,7 +144,6 @@ public void run() {
       activeMutationWorkers.incrementAndGet();
       try {
         while (!executorService.isShutdown()) {
-          Mutation mutation = null;
```
Comment (kevinsi4508) [inline bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutator.java]: Why is this removed?

File: bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutator.java [hunk 3]
```diff
@@ -202,7 +198,9 @@ public BigtableBufferedMutator(
         heapSizeManager.getMaxInFlightRpcs());
     this.options = options;
     this.heapSizeManager = heapSizeManager;
-    this.executorService = executorService;
+    this.executorService =
```
Comment (kevinsi4508) [inline bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutator.java]: This is a bit weird, this depends on "executorService" & "AsyncMutatorCount".
Why don't we always depend on AsyncMutatorCount. It it simpler:

public BigtableBufferedMutator(...)
  this(... options.getAsyncMutatorCount() > 0 ? createDefaultExecutorService() : null);
}

@VisibleForTesting
public BigtableBufferedMutator(...)
  ...
  this.executorService = executorService;
}

File: bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutator.java [hunk 4]
```diff
@@ -145,22 +151,13 @@ public void run() {
             if (operation == null || operation.isCloseMarker) {
               break;
             }
-            mutation = operation.mutation;
-            ListenableFuture<? extends GeneratedMessage> request =
-                issueRequest(operation.mutation, operation.operationId);
-            ExceptionCallback callback = new ExceptionCallback(operation.mutation);
-            Futures.addCallback(request, callback);
+            operation.run();
```
Comment (kevinsi4508) [inline bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutator.java]: Update doc to reflect this change.

File: bigtable-hbase-dataflow/src/main/java/com/google/cloud/bigtable/dataflow/CloudBigtableConfiguration.java (hunk 1 above)
Comment (sduskis) [inline bigtable-hbase-dataflow/src/main/java/com/google/cloud/bigtable/dataflow/CloudBigtableConfiguration.java]: I wanted to turn off this behavior for Dataflow by default, but keep it on everywhere else.

Comment (kevinsi4508) [inline bigtable-hbase-dataflow/src/main/java/com/google/cloud/bigtable/dataflow/CloudBigtableConfiguration.java]: Ok, please note a note here then.
Also, the override should use value: BIGTABLE_ASYNC_MUTATOR_COUNT_DEFAULT
not BigtableOptions.BIGTABLE_DATA_CHANNEL_COUNT_DEFAULT

Comment (sduskis) [inline bigtable-hbase-dataflow/src/main/java/com/google/cloud/bigtable/dataflow/CloudBigtableConfiguration.java]: Oh.  You mean the comment.  Woops.

Comment (sduskis) [inline bigtable-hbase-dataflow/src/main/java/com/google/cloud/bigtable/dataflow/CloudBigtableConfiguration.java]: Fixed.

File: bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutator.java (hunk 2 above)
Comment (sduskis) [inline bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutator.java]: it turned out to be superfluous.  issueRequest() handles the Exception case already.  This logic will never be invoked.

File: bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutator.java (hunk 4 above)
Comment (sduskis) [inline bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutator.java]: done.

**Comment by kevinsi4508** [comment]
LGTM
