### PR TITLE
 Fix FlatRowAdapter to properly handle hbase Result.

### LINKED ISSUE #1231: Bigtable HBase Exports are actually not compatible with HBase
Exports from Bigtable are no longer compatible with HBase.  The culprit is [`RowCell`](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-hbase-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/read/RowCell.java) which is a performance optimization for Cloud Bigtable scans.  It replaces HBase's [`KeyValue`](https://github.com/apache/hbase/blob/master/hbase-common/src/main/java/org/apache/hadoop/hbase/KeyValue.java) which is a great wire protocol, but caused performance bottlenecks for general Cloud Bigtable scans.

The solution is to translate `RowCell`s to `KeyValue` cells in the export process.  Bonus: have an option in the export process to allow `RowCell` for more performant disaster recovery backups.

### PR DESCRIPTION
**Pull request by igorbernstein2**
This should also fix #1231 & #1227

### CODE REVIEW

File: bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/util/ByteStringer.java [hunk 1]
```diff
@@ -54,6 +54,15 @@ public static ByteString wrap(final byte[] array) {
     return USE_ZEROCOPYBYTESTRING? ZeroCopyByteStringUtil.wrap(array): ByteString.copyFrom(array);
   }
 
+  /**
+   * Wraps a byte array in a {@link ByteString} without copying it.
+   */
+  public static ByteString wrap(final byte[] array, int offset, int length) {
+    return USE_ZEROCOPYBYTESTRING?
```
Comment (igorbernstein2) [inline bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/util/ByteStringer.java]: I think I'm missing something here...
When adapting hbase's Result, isn't it always the case that offset !=0? So this should prevent 3 array copies per cell?

File: bigtable-hbase-parent/bigtable-hbase/src/test/java/com/google/cloud/bigtable/hbase/adapters/read/TestFlatRowAdapter.java [hunk 2]
```diff
@@ -15,21 +15,28 @@
...
 import org.apache.hadoop.hbase.client.Result;
 import org.apache.hadoop.hbase.util.Bytes;
+import org.junit.Assert;
 import org.junit.Test;
 import org.junit.runner.RunWith;
 import org.junit.runners.JUnit4;
 
 import com.google.cloud.bigtable.grpc.scanner.FlatRow;
 import com.google.protobuf.ByteString;
+import org.omg.CORBA.TypeCode;
```
Comment (igorbernstein2) [inline bigtable-hbase-parent/bigtable-hbase/src/test/java/com/google/cloud/bigtable/hbase/adapters/read/TestFlatRowAdapter.java]: oops

File: bigtable-hbase-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/read/FlatRowAdapter.java [hunk 3]
```diff
@@ -75,7 +76,8 @@ private static RowCell toRowCell(byte[] rowKey, FlatRow.Cell cell, byte[] family
         // Bigtable timestamp has more granularity than HBase one. It is possible that Bigtable
         // cells are deduped unintentionally here. On the other hand, if we don't dedup them,
         // HBase will treat them as duplicates.
-        cell.getTimestamp() / TIME_CONVERSION_UNIT,
+        cell.getTimestamp() == HConstants.LATEST_TIMESTAMP ?
```
Comment (igorbernstein2) [inline bigtable-hbase-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/read/FlatRowAdapter.java]: done: #1236

**Comment by igorbernstein2** [comment]
rebased to include the timestamp change

File: bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/util/ByteStringer.java (hunk 1 above)
Comment (sduskis) [inline bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/util/ByteStringer.java]: When adapting a Result RowCell, `(offset == 0 && length == array.length)` will be true.

The 3 byte[] copies come into play for Puts that are sent via gRPC RPCs.  This case isn't an RPCE, but rather Dataflow's serialization process.  in the normal Dataflow serialization process, this will occur:

1. A scan happens, producing a Result generated from FlatRows.
2. Dataflow may serialize the Result 
3. if 2 occurs, deserialization occurs.

2 and 3 require byte array copies, regardless of whether the `Result` has `RowCells` or `KeyValue`s.  If the `Result` has `RowCell`s, there's no need to copy the `byte[]` as part of the serialization process.  If the `Result` has `KeyValue`s, then we the optimal solution would probably look different, and I don't think that case is something we should tackle in the Dataflow code, since it's not going to happen in production anyway.

**Comment by igorbernstein2** [comment]
Updated, PTAL.
