### PR TITLE
Fix #1770 Fuzzy keys with integer values above 127 match no rows

### LINKED ISSUE #1770: Fuzzy keys with integer values above 127 match no rows
As in #1703, we use keys that consist of multiple integers. We have found that with the 1.2.0 client, fuzzy filters are not correctly matching values above 127. This bug does not exist on version 1.0.0, where the filter works as expected. I did not try this with any other versions.

The sample program below should output all 8 keys. On version 1.0.0, it does. On version 1.2.0, it only outputs 4 keys - those with 126 or 127 in the 3rd position.

```java
public class FuzzyTest {
  private final Connection hbase;

  @Inject
  public FuzzyTest(Connection hbase) {
    this.hbase = hbase;
  }

  private byte[] createKey(int... values) {
    byte[] bytes = new byte[4 * values.length];
    for (int i = 0; i < values.length; i++) {
      System.arraycopy(Bytes.toBytes(values[i]), 0, bytes, 4 * i, 4);
    }
    return bytes;
  }

  private int[] parseKey(byte[] key) {
    int[] values = new int[key.length / 4];
    for (int i = 0; i < values.length; i++) {
      values[i] = Bytes.toInt(key, 4 * i);
    }
    return values;
  }

  public void run() throws Exception {
    String tableName = "fuzzy-test";
    String familyName = "data";
    HTableDescriptor tableDescriptor = new HTableDescriptor(TableName.valueOf(tableName));
    tableDescriptor.addFamily(new HColumnDescriptor(familyName));
    if (!hbase.getAdmin().tableExists(TableName.valueOf(tableName))) {
      hbase.getAdmin().createTable(tableDescriptor);
    }

    Table table = hbase.getTable(TableName.valueOf("fuzzy-test"));
    List<byte[]> keys = ImmutableList.of(
        createKey(5, 10, 126, 5),
        createKey(5, 11, 126, 7),
        createKey(5, 10, 127, 5),
        createKey(5, 11, 127, 7),
        createKey(5, 10, 128, 5),
        createKey(5, 11, 128, 7),
        createKey(5, 10, 129, 5),
        createKey(5, 11, 129, 7));
    List<Put> puts = keys.stream()
        .map(key -> new Put(key)
            .addColumn(Bytes.toBytes(familyName), Bytes.toBytes(0), Bytes.toBytes(0)))
        .collect(Collectors.toList());
    table.put(puts);

    // match keys with 5 in the first position and 126/127/128/129 in the 3rd position
    FuzzyRowFilter filter = new FuzzyRowFilter(ImmutableList.of(
        Pair.newPair(createKey(5, 0, 126, 0), createKey(0, 1, 0, 1)),
        Pair.newPair(createKey(5, 0, 127, 0), createKey(0, 1, 0, 1)),
        Pair.newPair(createKey(5, 0, 128, 0), createKey(0, 1, 0, 1)),
        Pair.newPair(createKey(5, 0, 129, 0), createKey(0, 1, 0, 1))));
    Scan scan = new Scan();
    scan.setFilter(filter);

    ResultScanner scanner = table.getScanner(scan);
    int matchedKeys = 0;
    for (Result r : scanner) {
      System.out.println(Arrays.toString(parseKey(r.getRow())));
      matchedKeys++;
    }
    System.out.println("Matched " + matchedKeys + " keys");
  }

  public static void main(String... args) throws Exception {
    final Injector injector = Guice.createInjector(new CoreModule());
    injector.getInstance(FuzzyTest.class).run();
  }
}
```

### PR DESCRIPTION
**Pull request by ajaaym**
Fix #1770 Fuzzy keys with integer values above 127 match no rows

### CODE REVIEW

File: bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java [hunk 1]
```diff
@@ -67,18 +67,12 @@
 import org.junit.experimental.categories.Category;
 
 import java.io.IOException;
-import java.util.ArrayList;
-import java.util.Arrays;
-import java.util.Collections;
-import java.util.List;
-import java.util.Set;
-import java.util.TreeSet;
+import java.util.*;
```
Comment (sduskis) [inline bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java]: Please revert the import of `*` and use individual imports.

File: bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java [hunk 2]
```diff
@@ -2051,19 +2044,15 @@ public void testFuzzyWithIntKeys() throws Exception {
...
-      assertMatchingRow(scanner.next(), keys.get(4));
-      assertMatchingRow(scanner.next(), keys.get(5));
-      assertMatchingRow(scanner.next(), keys.get(6));
-      assertMatchingRow(scanner.next(), keys.get(7));
-      assertNull(scanner.next());
+      scanner.forEach(r -> {
+        actualKeys.add(toFuzzyKeyString(CellUtil.cloneRow(r.rawCells()[0])));
+      });
     }
+    assertEquals(expectedKeys,actualKeys);
```
Comment (sduskis) [inline bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java]: Please use a space after `,`

File: bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java [hunk 3]
```diff
@@ -2051,19 +2044,15 @@ public void testFuzzyWithIntKeys() throws Exception {
         Pair.newPair(createKey(5, 0, 129, 0), createFuzzyMask(0, 1, 0, 1))));
 
     Scan scan = new Scan().setFilter(filter);
-
+    Set<String> expectedKeys = keys.stream().map(k ->toFuzzyKeyString(k)).collect(Collectors.toSet());
```
Comment (sduskis) [inline bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java]: Please add a space after `->`

**Comment by ajaaym** [comment]
@sduskis Can we upgrade integration-tests-common to 1.8 or keep it at 1.7?

**Comment by ajaaym** [comment]
@sduskis Fixed as per feedback, also fixed compilation for java 1.7. Build is failing bcz of timeout while downloading dependancy. Can you please resubmit the build?
